#' Predict method for linreg objects
#' 
#' @description Predicted values from an object of the class "linreg".
#' @param object An object of class "linreg", generated by a call to \code{\link{linreg}}.
#' @return A vector of predicted values.

pred <- function(object){
  y_hat <- as.vector(object$y_hat)
  return(y_hat)
}


