#' Predict method for linreg objects
#' 
#' @description Predicted values from an object of the class "linreg".
#' @param object An object of class "linreg", generated by a call to \code{\link{linreg}}.
#' @param ... additional arguments.
#' @return A vector of predicted values.
#' @examples 
#' linreg_obj <- linreg(Petal.Length~Species, datasets::iris)
#' pred(linreg_obj)
#' @export

pred <- function(object,...){
  y_hat <- as.vector(object$y_hat)
  return(y_hat)
}


