#' Print out the estimated coeffiencts 
#' 
#' @description Estimated coeffiencts from an object of class "linreg".
#' @param object An object of Class "linreg", generated by a call to \code{\link{linreg}}.
#' @param ... additional arguments.
#' @return A list of estimated coeffiencts.
#' @export

print.linreg <- function(object,...) {
  colnames(object$beta_hat) <- ""
  
  cat("Call:", sep="\n")
  cat("linreg(formula = ", object$y_name, " ", "~", " ", object$x_names, ", ","data = ", object$data_name, ")", sep = "")
  cat(" ", sep = "\n")
  cat("Coefficients:", sep="\n")
  print(as.matrix(t(object$beta_hat)))
}

