#' Residuals method for linreg objects
#' 
#' @description Residuals from an object of the class "linreg".
#' @param object An object of class "linreg", generated by a call to \code{\link{linreg}}.
#' @return A vector of residuals.

residuals.linreg <- function(object){
  e <- as.vector(object$e_hat)
  return(e)
}

